### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Dumpsterpog** [TheLastGamer18/easy-discord-chatbot#1]
It has been 15 minutes chat bot stopped working but few minutes back it was working fine it is showing token invalid at chat bot pls help

**Comment by TheLastGamer18** [comment]
Apologies for the inconvenience, it seems that the API used for fetching the reply seems to be not working, will try to find a workaround or a hotfix soon.

**Comment by TheLastGamer18** [comment]
After research, its happening to other packages too so there's nothing we can do other than waiting.

**Comment by Dumpsterpog** [comment]
Ohk thanks for responding so can I get the ur support sercer invite so that I can get the real time update

**Comment by Dumpsterpog** [comment]
Pls revert back on this many servers are waiting

**Comment by TheLastGamer18** [comment]
> Pls revert back on this many servers are waiting

There's nothing that I can do, it seems like an error from Brainshop itself so the best we can do is wait

**Comment by Dumpsterpog** [comment]
![image](https://user-images.githubusercontent.com/84399187/130248985-f5d68e66-17aa-4141-8923-604c2e4d470d.png)
pls help with this

**Comment by TheLastGamer18** [comment]
Is the bot sending multiple responses? Because as of now it should return "The chatbot endpoint is currently having issues and will be resolved asap." since it isn't working

**Comment by Dumpsterpog** [comment]
Yea sure u can take ur time

**Comment by Dumpsterpog** [comment]
And bot is also showing The chatbot endpoint is currently having issues

**Comment by Dumpsterpog** [comment]
Ok thanks chat bot is fully functional now !
