### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Day-Codes** [TheLastGamer18/easy-discord-chatbot#3]
The chat bot has not been loading for me and the issues keep going on for hours now

**Comment by Luuk-Dev** [comment]
When I look in the source code it's just using an API from https://api.affiliateplus.xyz. So if it doesn't work you can just send a fetch request with `node-fetch` to https://api.affiliateplus.xyz/api/chatbot?message=Some+message&botname=Some+bot+name and send the response of the page
